### ISSUE TITLE
pregen:config not working anymore on 1.20.4

### ISSUE THREAD

**Issue by Lyhtael** [GoldenDelicios/world-pregen#11]
Hello, 

I was trying to use your Pregen data pack (I love the think it load the minimap at the same time) but I have an error when it load pregen:config.

[22:44:04 ERROR]: Failed to load function pregen:config
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 12: Invalid chat component: Not a boolean: "true" at position 95: ...c":"true"}<--[HERE]
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 12: Invalid chat component: Not a boolean: "true" at position 95: ...c":"true"}<--[HERE]
        at net.minecraft.commands.functions.CommandFunction.fromLines(CommandFunction.java:73) ~[paper-1.20.4.jar:git-Paper-365]
        at net.minecraft.server.ServerFunctionLibrary.lambda$reload$2(ServerFunctionLibrary.java:80) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more

It happened in solo too. I linked the paper error cause it's more visual.
I tryed on 1.20.1 and it's working, I don't know what changed.

Ty by advance if you see this :)

**Comment by Lyhtael** [comment]
If founded the problem, i guess in 1.20.4 you can't avec "" for condition true on the line 12 and 13 in config.mcfunction

it's working

**Comment by sambobadger** [comment]
> If founded the problem, i guess in 1.20.4 you can't avec "" for condition true on the line 12 and 13 in config.mcfunction
> 
> it's working

Hi, I'm having the exact same issue, but I don't quite understand what you did so solve it? Could you explain what you did? It would be a great help. Thank you!

**Comment by Frontesque** [comment]
I've created a 1.20.4 build using the fix mentioned by @Lyhtael 
[Download](https://builds.frontesque.me/download.php?id=4&token=cn8OC3Hwqayi8mD1L8Yh45dFj3uw18mF)
![image](https://github.com/GoldenDelicios/world-pregen/assets/27463495/7236e9a2-d1e5-4e04-b2da-0f583b47d885)

**Comment by Lyhtael** [comment]
hi realy sorry i saw the github notif mail, i forget to respond realy sorry
I'm glad someone made the patch :)

**Comment by Frontesque** [comment]
Sadly my changes haven't been reviewed as of yet, and I don't especially want to take this project over, as it's not something that I use frequently. I'm not sure if @GoldenDelicios is still actively maintaining this project, but it appears that he isn't. Not sure if I'd be able to, or want to hack together a fix when 1.21 eventually comes out.

**Comment by GoldenDelicios** [comment]
Apologies for the delay, I had not noticed this issue. I try to keep this project maintained, especially after the release of major versions, although sometimes I forget or some change in a minor version can break the datapack.

This issue is solved in 1.4.
